/**
 * RC0 download utilities — isomorphic (no DOM/browser dependencies).
 */

import type { Rack, FxSlotData } from '../types/rack.js';
import type { MemoryConfig, MemoryBank } from '../types/memory-config.js';
import { EFFECT_NAME_MAP } from '../params/effect-map.js';

/** Clamp slot to 1-99 and zero-pad to 3 digits */
export function formatSlotNumber(slot: number): string {
  const clamped = Math.max(1, Math.min(99, Math.round(slot)));
  return String(clamped).padStart(3, '0');
}

/** Generate a plain-text readme describing the preset */
export function generateReadmeText(rack: Rack, slotNumber: number): string {
  const slot = formatSlotNumber(slotNumber);
  const lines: string[] = [
    `RC-505mk2 Preset: ${rack.title}`,
    `Generated by RC-505mk2 FX Rack Guide`,
    ``,
    `Memory Slot: ${parseInt(slot, 10)}`,
    `Files: MEMORY${slot}A.RC0, MEMORY${slot}B.RC0`,
  ];

  if (rack.genres?.length > 0) {
    lines.push(`Genres: ${rack.genres.join(', ')}`);
  }

  if (rack.description) {
    lines.push(``, `Description:`, `  ${rack.description}`);
  }

  lines.push(``);

  if (rack.inputFx.length > 0) {
    lines.push(`Input FX Chain:`);
    for (const fx of rack.inputFx) {
      const bank = fx.bank && fx.bank !== 'A' ? ` [Bank ${fx.bank}]` : '';
      const paramStr = fx.params.length > 0
        ? ` (${fx.params.map(p => `${p.name}=${p.value}`).join(', ')})`
        : '';
      lines.push(`  Slot ${fx.slot}${bank}: ${fx.effect}${paramStr}`);
    }
    lines.push(``);
  }

  if (rack.trackFx.length > 0) {
    lines.push(`Track FX Chain:`);
    for (const fx of rack.trackFx) {
      const bank = fx.bank && fx.bank !== 'A' ? ` [Bank ${fx.bank}]` : '';
      const paramStr = fx.params.length > 0
        ? ` (${fx.params.map(p => `${p.name}=${p.value}`).join(', ')})`
        : '';
      lines.push(`  Slot ${fx.slot}${bank}: ${fx.effect}${paramStr}`);
    }
    lines.push(``);
  }

  const s = rack.settings;
  if (s) {
    if (s.master?.tempo !== undefined) {
      lines.push(`Master Tempo: ${s.master.tempo} BPM`);
    }
    if (s.tracks?.length) {
      lines.push(`Track Settings:`);
      for (const t of s.tracks) {
        const parts: string[] = [];
        if (t.level !== undefined) parts.push(`Level=${t.level}`);
        if (t.pan !== undefined) parts.push(`Pan=${t.pan}`);
        if (t.reverse) parts.push(`Reverse=ON`);
        if (t.oneShot) parts.push(`1Shot=ON`);
        if (parts.length > 0) {
          lines.push(`  Track ${t.trackNumber}: ${parts.join(', ')}`);
        }
      }
    }
    if (s.master?.tempo !== undefined || s.tracks?.length) {
      lines.push(``);
    }
  }

  lines.push(
    `Installation:`,
    `1. Connect RC-505mk2 via USB (MENU > USB > STORAGE > CONNECT)`,
    `2. Back up the ROLAND folder on the device`,
    `3. Copy both .RC0 files into the ROLAND/DATA folder on the device`,
    `4. They replace the existing files for memory slot ${parseInt(slot, 10)}`,
    `5. Eject the drive and press EXIT on the device`,
  );

  return lines.join('\n');
}

/** Remap all FX slots in a rack to a specific bank */
export function remapRackToBank(rack: Rack, bank: 'A' | 'B' | 'C' | 'D'): Rack {
  if (bank === 'A') return rack;
  return {
    ...rack,
    inputFx: rack.inputFx.map((fx) => ({ ...fx, bank })),
    trackFx: rack.trackFx.map((fx) => ({ ...fx, bank })),
  };
}

const BUILDER_BANKS = ['A', 'B', 'C', 'D'] as const;

export interface BuilderBankState {
  rackId: string | null;
  rackTitle: string | null;
}

export interface BuilderExportState {
  slotNumber: number;
  memoryName: string;
  banks: Record<string, BuilderBankState>;
}

export function buildCompositeConfig(
  state: BuilderExportState,
  allRacks: Rack[],
): MemoryConfig {
  const rackMap = new Map(allRacks.map((r) => [r.id, r]));
  const inputBanks: MemoryBank[] = [];
  const trackBanks: MemoryBank[] = [];
  let firstRack: Rack | undefined;

  for (const bankId of BUILDER_BANKS) {
    const bankState = state.banks[bankId];
    if (!bankState?.rackId) continue;

    const rack = rackMap.get(bankState.rackId);
    if (!rack) continue;
    if (!firstRack) firstRack = rack;

    if (rack.inputFx.length > 0) {
      inputBanks.push({
        bank: bankId,
        slots: rack.inputFx.map((fx) => ({
          slot: fx.slot,
          effect: EFFECT_NAME_MAP[fx.effect.toUpperCase()] || fx.effect,
          label: fx.label,
          enabled: true,
          params: fx.params.map((p) => ({ name: p.name, value: p.value })),
        })),
      });
    }

    if (rack.trackFx.length > 0) {
      trackBanks.push({
        bank: bankId,
        slots: rack.trackFx.map((fx) => ({
          slot: fx.slot,
          effect: EFFECT_NAME_MAP[fx.effect.toUpperCase()] || fx.effect,
          label: fx.label,
          enabled: true,
          params: fx.params.map((p) => ({ name: p.name, value: p.value })),
        })),
      });
    }
  }

  return {
    version: 1,
    slotNumber: state.slotNumber,
    name: state.memoryName || firstRack?.title.slice(0, 12) || 'MEMORY',
    inputFx: { banks: inputBanks },
    trackFx: { banks: trackBanks },
    master: firstRack?.settings?.master,
    tracks: firstRack?.settings?.tracks?.map((t) => ({
      trackNumber: t.trackNumber,
      level: t.level,
      pan: t.pan,
      reverse: t.reverse,
      oneShot: t.oneShot,
      fx: t.fx,
      startMode: t.startMode,
      stopMode: t.stopMode,
    })),
  };
}

export function generateMemoryReadme(state: BuilderExportState, allRacks: Rack[]): string {
  const rackMap = new Map(allRacks.map((r) => [r.id, r]));
  const slot = formatSlotNumber(state.slotNumber);
  const lines: string[] = [
    `RC-505mk2 Memory: ${state.memoryName || 'Untitled'}`,
    `Generated by RC-505mk2 FX Rack Guide — Memory Builder`,
    ``,
    `Memory Slot: ${parseInt(slot, 10)}`,
    `Files: MEMORY${slot}A.RC0, MEMORY${slot}B.RC0`,
    ``,
    `Banks:`,
  ];

  for (const bankId of BUILDER_BANKS) {
    const bankState = state.banks[bankId];
    const rack = bankState?.rackId ? rackMap.get(bankState.rackId) : undefined;
    if (rack) {
      lines.push(`  Bank ${bankId}: ${rack.title}`);
      if (rack.inputFx.length > 0)
        lines.push(`    Input FX: ${rack.inputFx.map((f) => f.effect).join(' → ')}`);
      if (rack.trackFx.length > 0)
        lines.push(`    Track FX: ${rack.trackFx.map((f) => f.effect).join(' → ')}`);
    } else {
      lines.push(`  Bank ${bankId}: (empty)`);
    }
  }

  lines.push(
    ``,
    `Installation:`,
    `1. Connect RC-505mk2 via USB (MENU > USB > STORAGE > CONNECT)`,
    `2. Back up the ROLAND folder on the device`,
    `3. Copy both .RC0 files into the ROLAND/DATA folder on the device`,
    `4. They replace the existing files for memory slot ${parseInt(slot, 10)}`,
    `5. Eject the drive and press EXIT on the device`,
  );

  return lines.join('\n');
}
