/**
 * Embed the default.rc0 template as a TypeScript string constant.
 * Run before build: `tsx scripts/embed-template.ts`
 */

import { readFileSync, writeFileSync } from 'fs';
import { resolve, dirname } from 'path';
import { fileURLToPath } from 'url';

const __dirname = dirname(fileURLToPath(import.meta.url));
const templatePath = resolve(__dirname, '../test/fixtures/default.rc0');
const outputPath = resolve(__dirname, '../src/template/default-template.ts');

const template = readFileSync(templatePath, 'utf-8');

// Escape backticks and ${} in the template for template literal embedding
const escaped = template.replace(/\\/g, '\\\\').replace(/`/g, '\\`').replace(/\$\{/g, '\\${');

const output = `// Auto-generated by scripts/embed-template.ts — do not edit manually.
export const DEFAULT_TEMPLATE = \`${escaped}\`;
`;

writeFileSync(outputPath, output, 'utf-8');
console.log(`Embedded template (${template.length} chars) → ${outputPath}`);
